apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-poc
  labels:
    app: app-poc
spec:
  selector:
    matchLabels:
      app: app-poc
  template:
    metadata:
      labels:
        app: app-poc
    spec:
      containers:
        - name: app
          image: baseimage
          ports:
            - containerPort: 8080